// ---------------------------------
#define MAX_TISSUE_RADIUS 0
#define MIN_TISSUE_DISTANCE 0
#define NORMAL_TOILET_WATER_DISTANCE 0
#define THRESHOLD_MIN_TISSUE_PERCENTAGE 0
#define THRESHOLD_WATER_TISSUE_HAND_DISTANCE 0
#define THRESHOLD_IR_TEMPERATURE 0
#define THRESHOLD_FLUSHED_TIME 0
#define THRESHOLD_IR_CHECKED_TIME 0
#define TERM_CHANGE_OCCUPIED 0
#define WAIT_TOILET_COVER_CLOSED 0
#define MOTOR_WATER_TISSUE_PUSH_ANGLE 0
#define MOTOR_WATER_TISSUE_BACK_ANGLE 0
#define MOTOR_TOILET_COVER_PUSH_ANGLE 0
#define MOTOR_TOILET_COVER_BACK_ANGLE 0
#define MOTOR_CHECK_BROKEN_COVER_PUSH_ANGLE 0
#define MOTOR_CHECK_BROKEN_COVER_BACK_ANGLE 0
#define MOTOR_CHECK_BROKEN_COVER_DELAY 0
#define MOTOR_DELAY 0
#define PERIOD_CHECK_TISSUE 0
#define ESP_MUX_ID_RASPI 0
#define ESP_MUX_ID_BACKEND 0

// ---------------------------------

