/*
 * global_define.h
 *
 *  Created on: Feb 5, 2024
 *      Author: SSAFY
 */

#ifndef USERLIB_INC_GLOBAL_DEFINE_H_
#define USERLIB_INC_GLOBAL_DEFINE_H_


#define true 1
#define false 0

// kyr add MAX_STALL
#define MAX_STALL 3

#define MAX_TISSUE_RADIUS 10
#define MIN_TISSUE_DISTANCE 13
#define NORMAL_TOILET_WATER_DISTANCE 15
#define THRESHOLD_MIN_TISSUE_PERCENTAGE 0
#define THRESHOLD_WATER_TISSUE_HAND_DISTANCE 10
#define THRESHOLD_IR_TEMPERATURE 35
#define TERM_FLUSHED_TIME 10000U
#define THRESHOLD_IR_CHECKED_TIME 10000U
#define TERM_CHANGE_OCCUPIED 100  // 0 => 100
#define TERM_PUSH_TOILET_COVER 3000
#define WAIT_TOILET_FLUSH_DOWN 1000
#define MOTOR_WATER_TISSUE_PUSH_ANGLE 1000
#define MOTOR_WATER_TISSUE_BACK_ANGLE 500
#define MOTOR_TOILET_COVER_PUSH_ANGLE 1245 // 800 => 1200
#define MOTOR_TOILET_COVER_BACK_ANGLE 255
#define MOTOR_CHECK_BROKEN_COVER_PUSH_ANGLE 200
#define MOTOR_CHECK_BROKEN_COVER_BACK_ANGLE 800
#define MOTOR_CHECK_BROKEN_COVER_DELAY 0
#define MOTOR_DELAY 1000
#define PERIOD_CHECK_TISSUE 0
#define ESP_MUX_ID_RASPI 0
#define ESP_MUX_ID_BACKEND 0
#endif /* USERLIB_INC_GLOBAL_DEFINE_H_ */
